name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  debian:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-18, ubuntu-20]
    
    steps:
      - name: Checkout Main Archive
        uses: actions/checkout@v2
        with:
          path: tcltk
      
      - name: Checkout GSE4 Service
        uses: actions/checkout@v2
        with:
          repository: AT-VIE-EGSE/gse-gse4-service
          ref: master
          path: gse4-service
          token: ${{ secrets.ATVIEEGSEAUTO }}
          
      - name: Build Debian on ${{ matrix.os }}
        run: |	
          mkdir -p ./debdir
          rm -rf ./debdir/*
          ./tcltk/compile-base
          ./tcltk/compile-extras
          ./gse4-lib/build-deb -nobranchname -outdir ./debdir -allowdirty
      
      - name: Upload Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./debdir/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
